name: ci

on:
  pull_request:
  push:

jobs:
  linters:
    uses: ./.github/workflows/ci_linters.yml

  fedora:
    uses: ./.github/workflows/ci_rspamd.yml
    with:
      image: ghcr.io/fatalbanana/rspamd-build-docker:fedora-ci
      name: fedora-ci

  ubuntu:
    uses: ./.github/workflows/ci_rspamd.yml
    with:
      image: ghcr.io/fatalbanana/rspamd-build-docker:ubuntu-ci
      name: ubuntu-ci
